version: 1.9.1.{build}-{branch}
image: Visual Studio 2017
clone_folder: C:\Dev\Code\Projects\Driver Tools
environment:
  IS_APPVEYOR: 'true'
build_script:
  - ci_build "Antilli\Antilli.sln"
  - ci_build "DSCript\DScript.sln"
  - ci_build "GMC2Snooper\GMC2Snooper.sln"
  - ci_build "IMGRipper\IMGRipper.sln"
  - ci_build "Zartex\Zartex.sln"
  - ci_build "Audiose\Audiose.sln"
artifacts:
- path: Antilli\bin
  name: Antilli
- path: DScript\bin
  name: libDSC
- path: GMC2Snooper\bin
  name: GMC2Snooper
- path: IMGRipper\bin
  name: IMGRipper
- path: Zartex\bin
  name: Zartex
- path: Audiose\bin
  name: Audiose